# The token to authenticate with Musixmatch's API.
# If you get rate limited, you can obtain a new token with
# curl --location https://apic-desktop.musixmatch.com/ws/1.1/token.get?app_id=web-desktop-app-v1.0
musixmatch_token=2501192ac605cc2e16b6b2c04fe43d1011a38d919fe802976084e7

# Give .ja.lrc extensions to lyrics with Japanese characters. This can be used
# to give them a bigger font size by checking
# profile-cond=p['current-tracks/sub/lang']:sub(1, 1) == 'j'
mark_as_ja=no
